# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(599, 213)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 581, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rawText = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.rawText.setObjectName("rawText")
        self.verticalLayout.addWidget(self.rawText)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.convertButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.convertButton.setObjectName("convertButton")
        self.horizontalLayout.addWidget(self.convertButton)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.upperRadio = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.upperRadio.setObjectName("upperRadio")
        self.verticalLayout_2.addWidget(self.upperRadio)
        self.lowerRadio = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.lowerRadio.setObjectName("lowerRadio")
        self.verticalLayout_2.addWidget(self.lowerRadio)
        self.invertRadio = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.invertRadio.setObjectName("invertRadio")
        self.verticalLayout_2.addWidget(self.invertRadio)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.convertedText = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.convertedText.setReadOnly(True)
        self.convertedText.setObjectName("convertedText")
        self.verticalLayout.addWidget(self.convertedText)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.convertButton.setText(_translate("Dialog", "Zamień"))
        self.upperRadio.setText(_translate("Dialog", "Wielkie litery"))
        self.lowerRadio.setText(_translate("Dialog", "Małe litery"))
        self.invertRadio.setText(_translate("Dialog", "Odwróć"))
